// 本文件由 scripts/check-syntax-colors.mjs --write 生成，请勿手工编辑。
//
// 内容 = VS Code 深色主题继承链的 tokenColors 展开，顺序即优先级（同一 token 后者覆盖前者）：
//   dark_vs.json：tokenColors 50 条 → 展开 85 条
//   dark_plus.json：tokenColors 15 条 → 展开 84 条
//   dark_modern.json：tokenColors 0 条 → 展开 0 条
//   2026-dark.json：tokenColors 53 条 → 展开 91 条
// 组装语义对齐 <vscode>/src/vs/workbench/services/themes/common/colorThemeData.ts:103-152、:782-787：
// 被包含主题的规则排在前；默认色由 editor.foreground / editor.background 承担，主题里的空 scope 条目一律忽略。
//
// 为什么要在本仓库存一份：VS Code 从主题扩展的 JSON 读 tokenColors，而 npm 的 monaco-editor 发行包只内置
// 旧版 vs / vs-dark 规则（editor/standalone/common/themes.js），没有这条链的等价物 —— 缺口登记在
// docs/vscode-reference.md 第 5 节，由 scripts/check-syntax-colors.mjs 逐 token 比对。
//
// 末尾 41 条是「内置 vs_dark 有、主题链没有」的 token 的显式覆盖：PVF_DARK_THEME 以 vs-dark 为 base 且
// inherit 为 true，monaco 会把内置规则排在前面（standaloneThemeService.js:115-148），这些 token 会因此拿到旧版
// Dark+ 颜色而不是主题链的回落色；覆盖值即主题链对这些 token 的实际解析结果。
//
// 最后 4 条不属于主题链，都是本仓库的产品决定（偏差登记在 docs/vscode-reference.md 第 5 节）：
//   NUT（Squirrel）字符串 2 条 → Dark Modern / Dark+ 的 `string` 色 #ce9178（dark_vs.json 的 `string`）
//   注释 2 条 → Dark Modern / Dark+ 的 `comment` 色 #6A9955（dark_vs.json:80-84，VS Code 经典的注释绿；
//     2026-dark.json:300-306 已把 comment 改成灰 #8b949e）
// 都带语言段（`.squirrel` / `.pvf`），其它语言不受影响。
export const DARK_2026_TOKEN_RULES = [
	// ---- dark_vs.json ----
	{"token":"meta.embedded","foreground":"#D4D4D4"},
	{"token":"source.groovy.embedded","foreground":"#D4D4D4"},
	{"token":"string meta.image.inline.markdown","foreground":"#D4D4D4"},
	{"token":"variable.legacy.builtin.python","foreground":"#D4D4D4"},
	{"token":"emphasis","fontStyle":"italic"},
	{"token":"strong","fontStyle":"bold"},
	{"token":"header","foreground":"#000080"},
	{"token":"comment","foreground":"#6A9955"},
	{"token":"constant.language","foreground":"#569cd6"},
	{"token":"constant.numeric","foreground":"#b5cea8"},
	{"token":"variable.other.enummember","foreground":"#b5cea8"},
	{"token":"keyword.operator.plus.exponent","foreground":"#b5cea8"},
	{"token":"keyword.operator.minus.exponent","foreground":"#b5cea8"},
	{"token":"constant.regexp","foreground":"#646695"},
	{"token":"entity.name.tag","foreground":"#569cd6"},
	{"token":"entity.name.tag.css","foreground":"#d7ba7d"},
	{"token":"entity.name.tag.less","foreground":"#d7ba7d"},
	{"token":"entity.other.attribute-name","foreground":"#9cdcfe"},
	{"token":"entity.other.attribute-name.class.css","foreground":"#d7ba7d"},
	{"token":"source.css entity.other.attribute-name.class","foreground":"#d7ba7d"},
	{"token":"entity.other.attribute-name.id.css","foreground":"#d7ba7d"},
	{"token":"entity.other.attribute-name.parent-selector.css","foreground":"#d7ba7d"},
	{"token":"entity.other.attribute-name.parent.less","foreground":"#d7ba7d"},
	{"token":"source.css entity.other.attribute-name.pseudo-class","foreground":"#d7ba7d"},
	{"token":"entity.other.attribute-name.pseudo-element.css","foreground":"#d7ba7d"},
	{"token":"source.css.less entity.other.attribute-name.id","foreground":"#d7ba7d"},
	{"token":"entity.other.attribute-name.scss","foreground":"#d7ba7d"},
	{"token":"invalid","foreground":"#f44747"},
	{"token":"markup.underline","fontStyle":"underline"},
	{"token":"markup.bold","foreground":"#569cd6","fontStyle":"bold"},
	{"token":"markup.heading","foreground":"#569cd6","fontStyle":"bold"},
	{"token":"markup.italic","foreground":"#C586C0","fontStyle":"italic"},
	{"token":"markup.strikethrough","fontStyle":"strikethrough"},
	{"token":"markup.inserted","foreground":"#b5cea8"},
	{"token":"markup.deleted","foreground":"#ce9178"},
	{"token":"markup.changed","foreground":"#569cd6"},
	{"token":"punctuation.definition.quote.begin.markdown","foreground":"#6A9955"},
	{"token":"punctuation.definition.list.begin.markdown","foreground":"#6796e6"},
	{"token":"markup.inline.raw","foreground":"#ce9178"},
	{"token":"punctuation.definition.tag","foreground":"#808080"},
	{"token":"meta.preprocessor","foreground":"#569cd6"},
	{"token":"entity.name.function.preprocessor","foreground":"#569cd6"},
	{"token":"meta.preprocessor.string","foreground":"#ce9178"},
	{"token":"meta.preprocessor.numeric","foreground":"#b5cea8"},
	{"token":"meta.structure.dictionary.key.python","foreground":"#9cdcfe"},
	{"token":"meta.diff.header","foreground":"#569cd6"},
	{"token":"storage","foreground":"#569cd6"},
	{"token":"storage.type","foreground":"#569cd6"},
	{"token":"storage.modifier","foreground":"#569cd6"},
	{"token":"keyword.operator.noexcept","foreground":"#569cd6"},
	{"token":"string","foreground":"#ce9178"},
	{"token":"meta.embedded.assembly","foreground":"#ce9178"},
	{"token":"string.tag","foreground":"#ce9178"},
	{"token":"string.value","foreground":"#ce9178"},
	{"token":"string.regexp","foreground":"#d16969"},
	{"token":"punctuation.definition.template-expression.begin","foreground":"#569cd6"},
	{"token":"punctuation.definition.template-expression.end","foreground":"#569cd6"},
	{"token":"punctuation.section.embedded","foreground":"#569cd6"},
	{"token":"meta.template.expression","foreground":"#d4d4d4"},
	{"token":"support.type.vendored.property-name","foreground":"#9cdcfe"},
	{"token":"support.type.property-name","foreground":"#9cdcfe"},
	{"token":"source.css variable","foreground":"#9cdcfe"},
	{"token":"source.coffee.embedded","foreground":"#9cdcfe"},
	{"token":"keyword","foreground":"#569cd6"},
	{"token":"keyword.control","foreground":"#569cd6"},
	{"token":"keyword.operator","foreground":"#d4d4d4"},
	{"token":"keyword.operator.new","foreground":"#569cd6"},
	{"token":"keyword.operator.expression","foreground":"#569cd6"},
	{"token":"keyword.operator.cast","foreground":"#569cd6"},
	{"token":"keyword.operator.sizeof","foreground":"#569cd6"},
	{"token":"keyword.operator.alignof","foreground":"#569cd6"},
	{"token":"keyword.operator.typeid","foreground":"#569cd6"},
	{"token":"keyword.operator.alignas","foreground":"#569cd6"},
	{"token":"keyword.operator.instanceof","foreground":"#569cd6"},
	{"token":"keyword.operator.logical.python","foreground":"#569cd6"},
	{"token":"keyword.operator.wordlike","foreground":"#569cd6"},
	{"token":"keyword.other.unit","foreground":"#b5cea8"},
	{"token":"punctuation.section.embedded.begin.php","foreground":"#569cd6"},
	{"token":"punctuation.section.embedded.end.php","foreground":"#569cd6"},
	{"token":"support.function.git-rebase","foreground":"#9cdcfe"},
	{"token":"constant.sha.git-rebase","foreground":"#b5cea8"},
	{"token":"storage.modifier.import.java","foreground":"#d4d4d4"},
	{"token":"variable.language.wildcard.java","foreground":"#d4d4d4"},
	{"token":"storage.modifier.package.java","foreground":"#d4d4d4"},
	{"token":"variable.language","foreground":"#569cd6"},
	// ---- dark_plus.json ----
	{"token":"entity.name.function","foreground":"#DCDCAA"},
	{"token":"support.function","foreground":"#DCDCAA"},
	{"token":"support.constant.handlebars","foreground":"#DCDCAA"},
	{"token":"source.powershell variable.other.member","foreground":"#DCDCAA"},
	{"token":"entity.name.operator.custom-literal","foreground":"#DCDCAA"},
	{"token":"support.class","foreground":"#4EC9B0"},
	{"token":"support.type","foreground":"#4EC9B0"},
	{"token":"entity.name.type","foreground":"#4EC9B0"},
	{"token":"entity.name.namespace","foreground":"#4EC9B0"},
	{"token":"entity.other.attribute","foreground":"#4EC9B0"},
	{"token":"entity.name.scope-resolution","foreground":"#4EC9B0"},
	{"token":"entity.name.class","foreground":"#4EC9B0"},
	{"token":"storage.type.numeric.go","foreground":"#4EC9B0"},
	{"token":"storage.type.byte.go","foreground":"#4EC9B0"},
	{"token":"storage.type.boolean.go","foreground":"#4EC9B0"},
	{"token":"storage.type.string.go","foreground":"#4EC9B0"},
	{"token":"storage.type.uintptr.go","foreground":"#4EC9B0"},
	{"token":"storage.type.error.go","foreground":"#4EC9B0"},
	{"token":"storage.type.rune.go","foreground":"#4EC9B0"},
	{"token":"storage.type.cs","foreground":"#4EC9B0"},
	{"token":"storage.type.generic.cs","foreground":"#4EC9B0"},
	{"token":"storage.type.modifier.cs","foreground":"#4EC9B0"},
	{"token":"storage.type.variable.cs","foreground":"#4EC9B0"},
	{"token":"storage.type.annotation.java","foreground":"#4EC9B0"},
	{"token":"storage.type.generic.java","foreground":"#4EC9B0"},
	{"token":"storage.type.java","foreground":"#4EC9B0"},
	{"token":"storage.type.object.array.java","foreground":"#4EC9B0"},
	{"token":"storage.type.primitive.array.java","foreground":"#4EC9B0"},
	{"token":"storage.type.primitive.java","foreground":"#4EC9B0"},
	{"token":"storage.type.token.java","foreground":"#4EC9B0"},
	{"token":"storage.type.groovy","foreground":"#4EC9B0"},
	{"token":"storage.type.annotation.groovy","foreground":"#4EC9B0"},
	{"token":"storage.type.parameters.groovy","foreground":"#4EC9B0"},
	{"token":"storage.type.generic.groovy","foreground":"#4EC9B0"},
	{"token":"storage.type.object.array.groovy","foreground":"#4EC9B0"},
	{"token":"storage.type.primitive.array.groovy","foreground":"#4EC9B0"},
	{"token":"storage.type.primitive.groovy","foreground":"#4EC9B0"},
	{"token":"meta.type.cast.expr","foreground":"#4EC9B0"},
	{"token":"meta.type.new.expr","foreground":"#4EC9B0"},
	{"token":"support.constant.math","foreground":"#4EC9B0"},
	{"token":"support.constant.dom","foreground":"#4EC9B0"},
	{"token":"support.constant.json","foreground":"#4EC9B0"},
	{"token":"entity.other.inherited-class","foreground":"#4EC9B0"},
	{"token":"punctuation.separator.namespace.ruby","foreground":"#4EC9B0"},
	{"token":"keyword.control","foreground":"#C586C0"},
	{"token":"source.cpp keyword.operator.new","foreground":"#C586C0"},
	{"token":"keyword.operator.delete","foreground":"#C586C0"},
	{"token":"keyword.other.using","foreground":"#C586C0"},
	{"token":"keyword.other.directive.using","foreground":"#C586C0"},
	{"token":"keyword.other.operator","foreground":"#C586C0"},
	{"token":"entity.name.operator","foreground":"#C586C0"},
	{"token":"variable","foreground":"#9CDCFE"},
	{"token":"meta.definition.variable.name","foreground":"#9CDCFE"},
	{"token":"support.variable","foreground":"#9CDCFE"},
	{"token":"entity.name.variable","foreground":"#9CDCFE"},
	{"token":"constant.other.placeholder","foreground":"#9CDCFE"},
	{"token":"variable.other.constant","foreground":"#4FC1FF"},
	{"token":"variable.other.enummember","foreground":"#4FC1FF"},
	{"token":"meta.object-literal.key","foreground":"#9CDCFE"},
	{"token":"support.constant.property-value","foreground":"#CE9178"},
	{"token":"support.constant.font-name","foreground":"#CE9178"},
	{"token":"support.constant.media-type","foreground":"#CE9178"},
	{"token":"support.constant.media","foreground":"#CE9178"},
	{"token":"constant.other.color.rgb-value","foreground":"#CE9178"},
	{"token":"constant.other.rgb-value","foreground":"#CE9178"},
	{"token":"support.constant.color","foreground":"#CE9178"},
	{"token":"punctuation.definition.group.regexp","foreground":"#CE9178"},
	{"token":"punctuation.definition.group.assertion.regexp","foreground":"#CE9178"},
	{"token":"punctuation.definition.character-class.regexp","foreground":"#CE9178"},
	{"token":"punctuation.character.set.begin.regexp","foreground":"#CE9178"},
	{"token":"punctuation.character.set.end.regexp","foreground":"#CE9178"},
	{"token":"keyword.operator.negation.regexp","foreground":"#CE9178"},
	{"token":"support.other.parenthesis.regexp","foreground":"#CE9178"},
	{"token":"constant.character.character-class.regexp","foreground":"#d16969"},
	{"token":"constant.other.character-class.set.regexp","foreground":"#d16969"},
	{"token":"constant.other.character-class.regexp","foreground":"#d16969"},
	{"token":"constant.character.set.regexp","foreground":"#d16969"},
	{"token":"keyword.operator.or.regexp","foreground":"#DCDCAA"},
	{"token":"keyword.control.anchor.regexp","foreground":"#DCDCAA"},
	{"token":"keyword.operator.quantifier.regexp","foreground":"#d7ba7d"},
	{"token":"constant.character","foreground":"#569cd6"},
	{"token":"constant.other.option","foreground":"#569cd6"},
	{"token":"constant.character.escape","foreground":"#d7ba7d"},
	{"token":"entity.name.label","foreground":"#C8C8C8"},
	// ---- 2026-dark.json ----
	{"token":"comment","foreground":"#8b949e"},
	{"token":"punctuation.definition.comment","foreground":"#8b949e"},
	{"token":"string.comment","foreground":"#8b949e"},
	{"token":"constant.other.placeholder","foreground":"#ff7b72"},
	{"token":"constant.character","foreground":"#ff7b72"},
	{"token":"constant","foreground":"#79c0ff"},
	{"token":"entity.name.constant","foreground":"#79c0ff"},
	{"token":"variable.other.constant","foreground":"#79c0ff"},
	{"token":"variable.other.enummember","foreground":"#79c0ff"},
	{"token":"variable.language","foreground":"#79c0ff"},
	{"token":"entity","foreground":"#79c0ff"},
	{"token":"entity.name","foreground":"#ffa657"},
	{"token":"meta.export.default","foreground":"#ffa657"},
	{"token":"meta.definition.variable","foreground":"#ffa657"},
	{"token":"variable.parameter.function","foreground":"#c9d1d9"},
	{"token":"meta.jsx.children","foreground":"#c9d1d9"},
	{"token":"meta.block","foreground":"#c9d1d9"},
	{"token":"meta.tag.attributes","foreground":"#c9d1d9"},
	{"token":"entity.name.constant","foreground":"#c9d1d9"},
	{"token":"meta.object.member","foreground":"#c9d1d9"},
	{"token":"meta.embedded.expression","foreground":"#c9d1d9"},
	{"token":"entity.name.function","foreground":"#d2a8ff"},
	{"token":"entity.name.tag","foreground":"#7ee787"},
	{"token":"support.class.component","foreground":"#7ee787"},
	{"token":"keyword","foreground":"#ff7b72"},
	{"token":"storage","foreground":"#ff7b72"},
	{"token":"storage.type","foreground":"#ff7b72"},
	{"token":"storage.modifier.package","foreground":"#c9d1d9"},
	{"token":"storage.modifier.import","foreground":"#c9d1d9"},
	{"token":"storage.type.java","foreground":"#c9d1d9"},
	{"token":"string","foreground":"#a5d6ff"},
	{"token":"string punctuation.section.embedded source","foreground":"#a5d6ff"},
	{"token":"support","foreground":"#79c0ff"},
	{"token":"meta.property-name","foreground":"#79c0ff"},
	{"token":"variable","foreground":"#ffa657"},
	{"token":"variable.other","foreground":"#c9d1d9"},
	{"token":"invalid.broken","foreground":"#ffa198","fontStyle":"italic"},
	{"token":"invalid.deprecated","foreground":"#ffa198","fontStyle":"italic"},
	{"token":"invalid.illegal","foreground":"#ffa198","fontStyle":"italic"},
	{"token":"invalid.unimplemented","foreground":"#ffa198","fontStyle":"italic"},
	{"token":"carriage-return","foreground":"#f0f6fc","fontStyle":"italic underline"},
	{"token":"message.error","foreground":"#ffa198"},
	{"token":"string variable","foreground":"#79c0ff"},
	{"token":"source.regexp","foreground":"#a5d6ff"},
	{"token":"string.regexp","foreground":"#a5d6ff"},
	{"token":"string.regexp.character-class","foreground":"#a5d6ff"},
	{"token":"string.regexp constant.character.escape","foreground":"#a5d6ff"},
	{"token":"string.regexp source.ruby.embedded","foreground":"#a5d6ff"},
	{"token":"string.regexp string.regexp.arbitrary-repitition","foreground":"#a5d6ff"},
	{"token":"string.regexp constant.character.escape","foreground":"#7ee787","fontStyle":"bold"},
	{"token":"support.constant","foreground":"#79c0ff"},
	{"token":"support.variable","foreground":"#79c0ff"},
	{"token":"support.type.property-name.json","foreground":"#7ee787"},
	{"token":"meta.module-reference","foreground":"#79c0ff"},
	{"token":"punctuation.definition.list.begin.markdown","foreground":"#ffa657"},
	{"token":"markup.heading","foreground":"#79c0ff","fontStyle":"bold"},
	{"token":"markup.heading entity.name","foreground":"#79c0ff","fontStyle":"bold"},
	{"token":"markup.quote","foreground":"#7ee787"},
	{"token":"markup.italic","foreground":"#c9d1d9","fontStyle":"italic"},
	{"token":"markup.bold","foreground":"#c9d1d9","fontStyle":"bold"},
	{"token":"markup.underline","fontStyle":"underline"},
	{"token":"markup.strikethrough","fontStyle":"strikethrough"},
	{"token":"markup.inline.raw","foreground":"#79c0ff"},
	{"token":"markup.deleted","foreground":"#ffa198"},
	{"token":"meta.diff.header.from-file","foreground":"#ffa198"},
	{"token":"punctuation.definition.deleted","foreground":"#ffa198"},
	{"token":"punctuation.section.embedded","foreground":"#ff7b72"},
	{"token":"markup.inserted","foreground":"#7ee787"},
	{"token":"meta.diff.header.to-file","foreground":"#7ee787"},
	{"token":"punctuation.definition.inserted","foreground":"#7ee787"},
	{"token":"markup.changed","foreground":"#ffa657"},
	{"token":"punctuation.definition.changed","foreground":"#ffa657"},
	{"token":"markup.ignored","foreground":"#0d1117"},
	{"token":"markup.untracked","foreground":"#0d1117"},
	{"token":"meta.diff.range","foreground":"#d2a8ff","fontStyle":"bold"},
	{"token":"meta.diff.header","foreground":"#79c0ff"},
	{"token":"meta.separator","foreground":"#79c0ff","fontStyle":"bold"},
	{"token":"meta.output","foreground":"#79c0ff"},
	{"token":"brackethighlighter.tag","foreground":"#8b949e"},
	{"token":"brackethighlighter.curly","foreground":"#8b949e"},
	{"token":"brackethighlighter.round","foreground":"#8b949e"},
	{"token":"brackethighlighter.square","foreground":"#8b949e"},
	{"token":"brackethighlighter.angle","foreground":"#8b949e"},
	{"token":"brackethighlighter.quote","foreground":"#8b949e"},
	{"token":"brackethighlighter.unmatched","foreground":"#ffa198"},
	{"token":"constant.other.reference.link","foreground":"#a5d6ff"},
	{"token":"string.other.link","foreground":"#a5d6ff"},
	{"token":"token.info-token","foreground":"#6796E6"},
	{"token":"token.warn-token","foreground":"#CD9731"},
	{"token":"token.error-token","foreground":"#F44747"},
	{"token":"token.debug-token","foreground":"#B267E6"},
	// ---- 覆盖：内置 vs_dark 独家 token ----
	{"token":"variable.parameter","foreground":"#ffa657"},
	{"token":"meta.tag","foreground":"#bbbebf"},
	{"token":"variable.predefined","foreground":"#ffa657"},
	{"token":"number","foreground":"#bbbebf"},
	{"token":"number.hex","foreground":"#bbbebf"},
	{"token":"regexp","foreground":"#bbbebf"},
	{"token":"annotation","foreground":"#bbbebf"},
	{"token":"type","foreground":"#bbbebf"},
	{"token":"delimiter","foreground":"#bbbebf"},
	{"token":"delimiter.html","foreground":"#bbbebf"},
	{"token":"delimiter.xml","foreground":"#bbbebf"},
	{"token":"tag","foreground":"#bbbebf"},
	{"token":"tag.id","foreground":"#bbbebf"},
	{"token":"tag.id.pug","foreground":"#bbbebf"},
	{"token":"tag.class","foreground":"#bbbebf"},
	{"token":"tag.class.pug","foreground":"#bbbebf"},
	{"token":"meta.scss","foreground":"#bbbebf"},
	{"token":"metatag","foreground":"#bbbebf"},
	{"token":"metatag.content","foreground":"#bbbebf"},
	{"token":"metatag.content.html","foreground":"#bbbebf"},
	{"token":"metatag.html","foreground":"#bbbebf"},
	{"token":"metatag.xml","foreground":"#bbbebf"},
	{"token":"metatag.php","foreground":"#bbbebf","fontStyle":""},
	{"token":"key","foreground":"#bbbebf"},
	{"token":"string.key.json","foreground":"#a5d6ff"},
	{"token":"attribute.name","foreground":"#bbbebf"},
	{"token":"attribute.value","foreground":"#bbbebf"},
	{"token":"attribute.value.number","foreground":"#bbbebf"},
	{"token":"attribute.value.number.css","foreground":"#bbbebf"},
	{"token":"attribute.value.unit","foreground":"#bbbebf"},
	{"token":"attribute.value.unit.css","foreground":"#bbbebf"},
	{"token":"attribute.value.hex","foreground":"#bbbebf"},
	{"token":"attribute.value.hex.css","foreground":"#bbbebf"},
	{"token":"string.sql","foreground":"#a5d6ff"},
	{"token":"keyword.flow","foreground":"#ff7b72"},
	{"token":"keyword.json","foreground":"#ff7b72"},
	{"token":"keyword.flow.scss","foreground":"#ff7b72"},
	{"token":"operator.scss","foreground":"#bbbebf"},
	{"token":"operator.sql","foreground":"#bbbebf"},
	{"token":"operator.swift","foreground":"#bbbebf"},
	{"token":"predefined.sql","foreground":"#bbbebf"},
	// ---- 覆盖：NUT（Squirrel）字符串（本仓库产品决定，见 docs/vscode-reference.md 第 5 节） ----
	{"token":"string.quoted.double.squirrel","foreground":"#CE9178"},
	{"token":"string.quoted.single.squirrel","foreground":"#CE9178"},
	// ---- 覆盖：注释（PVF 文本 + NUT，本仓库产品决定，见 docs/vscode-reference.md 第 5 节） ----
	{"token":"comment.pvf","foreground":"#6A9955"},
	{"token":"comment.squirrel","foreground":"#6A9955"},
];
